In [8]:
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

In [4]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [9]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)

    def forward(self,x):
        return self.linear(x)

In [13]:
model=LinearRegressionModel()
print(list(model.parameters()))
optimizer=optim.SGD(model.parameters(), lr=0.01)

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [17]:
nb_epochs=2000
for epoch in range(nb_epochs):
    prediction=model(x_data)
    cost=F.mse_loss(prediction,t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print('Epoch:',epoch, 'Cost:', cost.item())

Epoch: 0 Cost: 1.2523742043413222e-09
Epoch: 400 Cost: 7.644303245957218e-11
Epoch: 800 Cost: 7.644303245957218e-11
Epoch: 1200 Cost: 7.644303245957218e-11
Epoch: 1600 Cost: 7.644303245957218e-11


In [19]:
new_data=torch.FloatTensor([[10]])
y_pred=model(new_data)
print(y_pred)
print(list(model.parameters()))

tensor([[21.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [20]:
x1_data=torch.FloatTensor([[73., 80., 75.],
            [93., 88., 93.],
            [89., 91., 90.],
            [96., 98., 100.],
            [73., 66., 70.]])
t1_data=torch.FloatTensor([[152.],[185.],[180.],[196.],[142.]])

In [44]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self,x):
        return self.linear(x)

In [45]:
model1=MultiLinearRegressionModel()
print(list(model1.parameters()))
optimizer1=optim.SGD(model1.parameters(), lr=1e-6)

[Parameter containing:
tensor([[-0.0421, -0.0520,  0.0837]], requires_grad=True), Parameter containing:
tensor([-0.0023], requires_grad=True)]


In [46]:
nb1_epochs=100000
for epoch in range(nb1_epochs):
    prediction=model1(x1_data)
    cost=F.mse_loss(prediction, t1_data)

    optimizer1.zero_grad()
    cost.backward()
    optimizer1.step()

    if epoch%400==0:
        print("Epoch:", epoch, "Cost:", cost.item())

Epoch: 0 Cost: 29938.337890625
Epoch: 400 Cost: 1.4944742918014526
Epoch: 800 Cost: 1.471176266670227
Epoch: 1200 Cost: 1.4483835697174072
Epoch: 1600 Cost: 1.4260575771331787
Epoch: 2000 Cost: 1.4042048454284668
Epoch: 2400 Cost: 1.3827892541885376
Epoch: 2800 Cost: 1.3618205785751343
Epoch: 3200 Cost: 1.3413043022155762
Epoch: 3600 Cost: 1.3212344646453857
Epoch: 4000 Cost: 1.301565408706665
Epoch: 4400 Cost: 1.28230619430542
Epoch: 4800 Cost: 1.2634353637695312
Epoch: 5200 Cost: 1.2449910640716553
Epoch: 5600 Cost: 1.2269186973571777
Epoch: 6000 Cost: 1.2092150449752808
Epoch: 6400 Cost: 1.1919076442718506
Epoch: 6800 Cost: 1.17494797706604
Epoch: 7200 Cost: 1.1583399772644043
Epoch: 7600 Cost: 1.142051100730896
Epoch: 8000 Cost: 1.1261521577835083
Epoch: 8400 Cost: 1.110554814338684
Epoch: 8800 Cost: 1.0952832698822021
Epoch: 9200 Cost: 1.0803312063217163
Epoch: 9600 Cost: 1.065697193145752
Epoch: 10000 Cost: 1.051345944404602
Epoch: 10400 Cost: 1.0373204946517944
Epoch: 10800 Cost

In [43]:
print(list(model1.parameters()))
new_data1=torch.FloatTensor([[80,80,90]])
y_pred1=model1(new_data1)
print(y_pred1)

[Parameter containing:
tensor([[0.8652, 0.4444, 0.7031]], requires_grad=True), Parameter containing:
tensor([-0.2053], requires_grad=True)]
tensor([[167.8380]], grad_fn=<AddmmBackward0>)
