# 파이토치 기본문법 

In [1]:
import torch

In [2]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [3]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
print(torch.tensor([[1,2],[3,4]]))
# print(torch.tensor([[1,2],[3,4]],device='cuda:0'))
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [5]:
ft=torch.FloatTensor([[1,2],[3,4]])
lt=torch.LongTensor([[1,2],[3,4]])
bt=torch.ByteTensor([[1,2],[3,4]])
print(ft)
print(lt)
print(bt)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


### numpy와 tensor는 호환이 됨
ndarry->torch tensor->ndarray  

In [6]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
print(x, type(x))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [8]:
tx=torch.from_numpy(x)
print(tx,type(tx))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32) <class 'torch.Tensor'>


In [9]:
nx=tx.numpy()
print(nx,type(nx))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


### tensor 형 변환

In [10]:
ft=tx.float()
print(ft, type(ft))
lt=ft.long()
print(lt,type(lt))
bt=ft.byte()
print(bt,type(bt))

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) <class 'torch.Tensor'>
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) <class 'torch.Tensor'>
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.uint8) <class 'torch.Tensor'>


### 3차원 만들기

In [11]:
na=np.arange(1,13).reshape(3,2,2)
na

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [12]:
t=torch.from_numpy(na)
t

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)

### 크기 구하기 

In [13]:
print(t.size())
print(t.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [14]:
print(t.size(0))
print(t.shape[1])
print(t.size(-1))
print(t.shape[-3])

3
2
2
3


In [15]:
print(t.dim())
print(len(t.size()))

3
3


In [16]:
a=torch.Tensor([[1,2],[3,4]])
b=torch.Tensor([[1,2],[3,4]])

In [17]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a==b)
print(a!=b)
print(a**b)

tensor([[2., 4.],
        [6., 8.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[True, True],
        [True, True]])
tensor([[False, False],
        [False, False]])
tensor([[  1.,   4.],
        [ 27., 256.]])


In [18]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a//2) #정수 몫만 구하기
print(a==2)
print(a>2)
print(a!=2)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[0., 1.],
        [1., 2.]])
tensor([[False,  True],
        [False, False]])
tensor([[False, False],
        [ True,  True]])
tensor([[ True, False],
        [ True,  True]])


### 벡터 연산

In [19]:
c=torch.tensor([1,2])
print(a)
print(a+c)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [4., 6.]])


In [20]:
print(a)
print(b)
print(a.mul(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[1., 2.],
        [3., 4.]])


### inplace 연산: 함수의 '_' 의 경우 실제 값이 변함

In [21]:
print(a.mul_(b))
print(a)

tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])


In [22]:
print(a)
print(a.sum())
print(a.sum(dim=0))
print(a.sum(dim=1))
print(a.sum(dim=-1))

tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor(30.)
tensor([10., 20.])
tensor([ 5., 25.])
tensor([ 5., 25.])


In [23]:
print(t)
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=2))

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[15, 18],
        [21, 24]])
tensor([[ 4,  6],
        [12, 14],
        [20, 22]])
tensor([[ 3,  7],
        [11, 15],
        [19, 23]])


In [24]:
ft=t.float()
print(ft.mean())
print(ft.mean(dim=0))
print(ft.mean(dim=1))
print(ft.mean(dim=2))

tensor(6.5000)
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])
tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])


In [52]:
x=torch.arange(1,13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
print(x.view(3,4))
print(x.reshape(3,4))
print(x.view(4,3))
print(x.view(3,2,2))
print(x.view(-1,2,3))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [53]:
x1=x.view(2,3,1,2)
print(x1)

tensor([[[[ 1,  2]],

         [[ 3,  4]],

         [[ 5,  6]]],


        [[[ 7,  8]],

         [[ 9, 10]],

         [[11, 12]]]])


In [64]:
print(x1.squeeze_())

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])


In [67]:
print(x1.unsqueeze(0))

tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]])


# 텐서 자르기

# 텐서 합치기

In [78]:
x=torch.arange(1,13).view(2,2,3)
y=torch.arange(11,23).view(2,2,3)
print(x)
print(y)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])


In [97]:
z=torch.cat([x,y],dim=1)
z

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [11, 12, 13],
         [14, 15, 16]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [17, 18, 19],
         [20, 21, 22]]])

In [98]:
z=torch.stack([x,y], dim=1)
z

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[11, 12, 13],
          [14, 15, 16]]],


        [[[ 7,  8,  9],
          [10, 11, 12]],

         [[17, 18, 19],
          [20, 21, 22]]]])

In [100]:
x=torch.randperm(3**3).view(3,3,3)
x

tensor([[[ 1, 18, 19],
         [ 5,  0,  6],
         [ 4, 14,  9]],

        [[ 8, 24,  3],
         [15, 23, 26],
         [25, 21,  2]],

        [[ 7, 20, 17],
         [10, 13, 12],
         [11, 16, 22]]])

In [104]:
y=x.argmax(dim=1)
y

tensor([[1, 0, 0],
        [2, 0, 1],
        [2, 0, 2]])

In [110]:
value, indices=torch.topk(x, k=1, dim=1)
print(value)
[print(indices)]

tensor([[[ 5, 18, 19]],

        [[25, 24, 26]],

        [[11, 20, 22]]])
tensor([[[1, 0, 0]],

        [[2, 0, 1]],

        [[2, 0, 2]]])


[None]

In [113]:
x=torch.randperm(9).view(3,3)
x

tensor([[5, 7, 3],
        [6, 8, 0],
        [4, 1, 2]])

In [117]:
mask=x<4
mask

tensor([[False, False,  True],
        [False, False,  True],
        [False,  True,  True]])

In [118]:
y=x.masked_fill(mask, value=0)
y

tensor([[5, 7, 0],
        [6, 8, 0],
        [4, 0, 0]])