# python
경사하강법

In [3]:
import numpy as np

### y=wx+b 함수
- w = 2
- b = 1

In [19]:
x_data=np.array([1,2,3,4,5]).reshape(5,1)
t_data=np.array([4,5,8,9,11]).reshape(5,1)

In [14]:
w=np.random.rand(1,1)
b=np.random.rand(1)
print(w,b)

[[0.14638981]] [0.145036]


In [20]:
def loss_func(x,t):
    y=np.dot(x,w)+b

    return (np.sum((t-y)**2)/len(x))

In [9]:
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)

        x[idx]= tmp_val-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad

In [11]:
def predict(x):
    y=np.dot(x, w)+b
    return y

In [21]:
learning_rate=1e-2
f=lambda x: loss_func(x_data, t_data)
print("Initial error value=", loss_func(x_data, t_data), "Inital w=", w, "b=", b)

for step in range(8001):
    w-=learning_rate*numerical_derivative(f,w)
    b-=learning_rate*numerical_derivative(f,b)

    if step % 400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=", w, "b=", b)

Initial error value= 0.40000000000000924 Inital w= [[2.]] b= [1.]
step= 0 error value= 0.37230940159997583 w= [[2.016]] b= [1.00704]
step= 400 error value= 0.17117499500665231 w= [[1.86864682]] b= [1.75222387]
step= 800 error value= 0.16071303074769427 w= [[1.81734007]] b= [1.93741217]
step= 1200 error value= 0.16004549557712175 w= [[1.80438007]] b= [1.98419042]
step= 1600 error value= 0.16000290288678873 w= [[1.8011064]] b= [1.99600653]
step= 2000 error value= 0.16000018522133894 w= [[1.80027947]] b= [1.99899126]
step= 2400 error value= 0.1600000118182164 w= [[1.80007059]] b= [1.99974519]
step= 2800 error value= 0.16000000075407184 w= [[1.80001783]] b= [1.99993564]
step= 3200 error value= 0.16000000004811435 w= [[1.8000045]] b= [1.99998374]
step= 3600 error value= 0.16000000000307021 w= [[1.80000114]] b= [1.99999589]
step= 4000 error value= 0.16000000000019585 w= [[1.80000029]] b= [1.99999896]
step= 4400 error value= 0.1600000000000124 w= [[1.80000007]] b= [1.99999974]
step= 4800 erro

In [23]:
predict(10)

array([[20.]])

In [24]:
x_data=np.array([[1,1.5],[2,2.5],[3,3.5],[4,4.5],[5,5.5]]).reshape(5,2)
t_data=np.array([4,5,8,9,11]).reshape(5,1)

In [25]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w,b)

[[0.72421819]
 [0.47740649]] [0.89809539]


In [ ]:
def loss_func(x,t):
    y=np.dot(x,w)+b

    return (np.sum((t-y)**2)/len(x))

In [26]:
learning_rate=1e-2
f=lambda x: loss_func(x_data, t_data)
print("Initial error value=", loss_func(x_data, t_data), "Inital w=", w, "b=", b)

for step in range(8001):
    w-=learning_rate*numerical_derivative(f,w)
    b-=learning_rate*numerical_derivative(f,b)

    if step % 400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=", w, "b=", b)

Initial error value= 7.9428101194478815 Inital w= [[0.72421819]
 [0.47740649]] b= [0.89809539]
step= 0 error value= 2.0543606985312626 w= [[0.90765284]
 [0.68742442]] b= [0.9255546]
step= 400 error value= 0.16405925548537786 w= [[0.91156425]
 [0.93003001]] b= [1.38572589]
step= 800 error value= 0.1602454407445239 w= [[0.86952028]
 [0.94070755]] b= [1.49294412]
step= 1200 error value= 0.16001484044532022 w= [[0.85918187]
 [0.94333311]] b= [1.51930857]
step= 1600 error value= 0.16000089731970846 w= [[0.8566397 ]
 [0.94397872]] b= [1.52579147]
step= 2000 error value= 0.16000005425596328 w= [[0.8560146 ]
 [0.94413747]] b= [1.52738558]
step= 2400 error value= 0.16000000328055802 w= [[0.85586089]
 [0.94417651]] b= [1.52777757]
step= 2800 error value= 0.1600000001983573 w= [[0.85582309]
 [0.94418611]] b= [1.52787395]
step= 3200 error value= 0.16000000001199394 w= [[0.8558138 ]
 [0.94418847]] b= [1.52789765]
step= 3600 error value= 0.16000000000072487 w= [[0.85581151]
 [0.94418905]] b= [1.5279

In [28]:
predict(10)

array([[10.08601303],
       [10.96979773]])

## 실습

In [29]:
import numpy as np

x_data1 = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
t_data1 = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

x_data=np.array(x_data1)
t_data=np.array(t_data1)
print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [46]:
w=np.random.rand(3,1)
b=np.random.rand(1)
print(w,b)

[[0.06466073]
 [0.34969779]
 [0.70928219]] [0.15122754]


In [50]:
learning_rate=1e-5
f=lambda x: loss_func(x_data, t_data)
print("Initial error value=", loss_func(x_data, t_data), "Inital w=", w, "b=", b)

for step in range(100001):
    w-=learning_rate*numerical_derivative(f,w)
    b-=learning_rate*numerical_derivative(f,b)

    if step % 4000==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=", w, "b=", b)

Initial error value= 0.16576549155371129 Inital w= [[1.0047692 ]
 [0.50072803]
 [0.50421402]] b= [0.25175755]
step= 0 error value= 0.16576520150205493 w= [[1.00477008]
 [0.50072848]
 [0.50421271]] b= [0.25175798]
step= 100 error value= 0.16573626555346008 w= [[1.00485852]
 [0.50077269]
 [0.50408113]] b= [0.25180097]


In [48]:
predict([73.,80.,75.])

array([151.4740336])