In [29]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [30]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [31]:
model=nn.Linear(1,1)    # input_dim=1, output_dim=1
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [32]:
optimizer=optim.SGD(model.parameters(),lr=0.01)

In [33]:
nb_epochs=20000

for epoch in range(nb_epochs):
    prediction=model(x_data)
    cost=F.mse_loss(prediction,t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print('Epoch:',epoch, 'Cost:', cost.item())

Epoch: 0 Cost: 39.16685104370117
Epoch: 400 Cost: 0.01109258271753788
Epoch: 800 Cost: 0.0007385412463918328
Epoch: 1200 Cost: 4.91717473778408e-05
Epoch: 1600 Cost: 3.276181814726442e-06
Epoch: 2000 Cost: 2.1860606125301274e-07
Epoch: 2400 Cost: 1.4702209227834828e-08
Epoch: 2800 Cost: 9.986707016906848e-10
Epoch: 3200 Cost: 1.0809344391793374e-10
Epoch: 3600 Cost: 5.426272625674855e-11
Epoch: 4000 Cost: 5.426272625674855e-11
Epoch: 4400 Cost: 5.426272625674855e-11
Epoch: 4800 Cost: 5.426272625674855e-11
Epoch: 5200 Cost: 5.426272625674855e-11
Epoch: 5600 Cost: 5.426272625674855e-11
Epoch: 6000 Cost: 5.426272625674855e-11
Epoch: 6400 Cost: 5.426272625674855e-11
Epoch: 6800 Cost: 5.426272625674855e-11
Epoch: 7200 Cost: 5.426272625674855e-11
Epoch: 7600 Cost: 5.426272625674855e-11
Epoch: 8000 Cost: 5.426272625674855e-11
Epoch: 8400 Cost: 5.426272625674855e-11
Epoch: 8800 Cost: 5.426272625674855e-11
Epoch: 9200 Cost: 5.426272625674855e-11
Epoch: 9600 Cost: 5.426272625674855e-11
Epoch: 10

In [34]:
new_data=torch.FloatTensor([[10]])
y_pred=model(new_data)
print(y_pred)
print(list(model.parameters()))


tensor([[21.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [35]:
x1_data=torch.FloatTensor([[73., 80., 75.],
            [93., 88., 93.],
            [89., 91., 90.],
            [96., 98., 100.],
            [73., 66., 70.]])
t1_data=torch.FloatTensor([[152.],[185.],[180.],[196.],[142.]])

In [36]:
model1=nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [37]:
optimizer1=optim.SGD(model1.parameters(),lr=1e-6)

In [49]:
nb1_epochs=20000
for epoch in range(nb1_epochs):
    prediction=model1(x1_data)
    cost=F.mse_loss(prediction, t1_data)

    optimizer1.zero_grad()
    cost.backward()
    optimizer1.step()

    if epoch%400==0:
        print("Epoch:", epoch, "Cost:", cost.item())

Epoch: 0 Cost: 0.162821963429451
Epoch: 400 Cost: 0.16280606389045715
Epoch: 800 Cost: 0.16280034184455872
Epoch: 1200 Cost: 0.16278302669525146
Epoch: 1600 Cost: 0.16277779638767242
Epoch: 2000 Cost: 0.16276618838310242
Epoch: 2400 Cost: 0.1627521961927414
Epoch: 2800 Cost: 0.1627405434846878
Epoch: 3200 Cost: 0.16273128986358643
Epoch: 3600 Cost: 0.1627214103937149
Epoch: 4000 Cost: 0.1627081036567688
Epoch: 4400 Cost: 0.1626988798379898
Epoch: 4800 Cost: 0.16268983483314514
Epoch: 5200 Cost: 0.16267384588718414
Epoch: 5600 Cost: 0.1626654714345932
Epoch: 6000 Cost: 0.162654310464859
Epoch: 6400 Cost: 0.16264666616916656
Epoch: 6800 Cost: 0.16263927519321442
Epoch: 7200 Cost: 0.16263166069984436
Epoch: 7600 Cost: 0.1626148521900177
Epoch: 8000 Cost: 0.16260822117328644
Epoch: 8400 Cost: 0.1625967174768448
Epoch: 8800 Cost: 0.16258420050144196
Epoch: 9200 Cost: 0.16258014738559723
Epoch: 9600 Cost: 0.16256698966026306
Epoch: 10000 Cost: 0.16255801916122437
Epoch: 10400 Cost: 0.1625455

In [51]:
print(list(model1.parameters()))
new_data1=torch.FloatTensor([[80,80,90]])
y_pred1=model1(new_data1)
print(y_pred1)

[Parameter containing:
tensor([[1.0694, 0.5347, 0.4056]], requires_grad=True), Parameter containing:
tensor([0.3584], requires_grad=True)]
tensor([[165.1861]], grad_fn=<AddmmBackward0>)
