In [22]:
import torch
import torch.nn.functional as F

## softmax() 함수 

In [2]:
z=torch.FloatTensor([1,2,3])
y_hat=F.softmax(z, dim=0)
print(y_hat)
print(y_hat.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [6]:
z=torch.rand(3,5, requires_grad=True)
y_hat=F.softmax(z, dim=1)
print(y_hat)
print(y_hat.sum(dim=1))

tensor([[0.2602, 0.1434, 0.3212, 0.1348, 0.1405],
        [0.3169, 0.1520, 0.1578, 0.2258, 0.1476],
        [0.1212, 0.1192, 0.2568, 0.2047, 0.2981]], grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)


## one_hot 인코딩 구현 

In [18]:
y=torch.randint(5,(3,)).long()
y

tensor([4, 2, 3])

In [19]:
y_one_hot=torch.zeros_like(y_hat)
print(y_one_hot)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [20]:
y_one_hot.scatter_(1, y.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])


In [21]:
print(y.unsqueeze(1))

tensor([[4],
        [2],
        [3]])


## 소프트맥스 모델

In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [24]:
torch.manual_seed(1)

In [27]:
x_data=[[1,2,1,1],
           [2,1,3,2],
           [3,1,3,4],
           [4,1,5,5],
           [1,7,5,5],
           [1,2,5,6],
           [1,6,6,6],
           [1,7,7,7]]
y_data=[2,2,2,1,1,1,0,0]
x_train=torch.FloatTensor(x_data)
y_train=torch.LongTensor(y_data)
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [29]:
y_one_hot=torch.zeros(8,3)
y_one_hot.scatter_(1, y_train.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [30]:
W=torch.zeros((4,3),requires_grad=True)
b=torch.zeros((1,3),requires_grad=True)
optimizer=optim.SGD([W,b], lr=0.1)

In [34]:
n_epochs=10000
for epoch in range(n_epochs):
    y_hat=F.softmax(x_train.matmul(W)+b, dim=1)
    cost=(y_one_hot * -torch.log(y_hat)).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print('Epoch:', epoch, 'Cost:', cost.item()) 

Epoch: 0 Cost: 0.03978875279426575
Epoch: 100 Cost: 0.039412543177604675
Epoch: 200 Cost: 0.039043426513671875
Epoch: 300 Cost: 0.03868097439408302
Epoch: 400 Cost: 0.038325224071741104
Epoch: 500 Cost: 0.03797595947980881
Epoch: 600 Cost: 0.03763280808925629
Epoch: 700 Cost: 0.03729577362537384
Epoch: 800 Cost: 0.03696456551551819
Epoch: 900 Cost: 0.03663923218846321
Epoch: 1000 Cost: 0.03631956875324249
Epoch: 1100 Cost: 0.03600522503256798
Epoch: 1200 Cost: 0.03569631651043892
Epoch: 1300 Cost: 0.035392582416534424
Epoch: 1400 Cost: 0.03509405627846718
Epoch: 1500 Cost: 0.03480030223727226
Epoch: 1600 Cost: 0.03451148793101311
Epoch: 1700 Cost: 0.03422728180885315
Epoch: 1800 Cost: 0.03394775837659836
Epoch: 1900 Cost: 0.03367269039154053
Epoch: 2000 Cost: 0.03340194374322891
Epoch: 2100 Cost: 0.03313552588224411
Epoch: 2200 Cost: 0.03287333995103836
Epoch: 2300 Cost: 0.032615192234516144
Epoch: 2400 Cost: 0.03236100450158119
Epoch: 2500 Cost: 0.03211076185107231
Epoch: 2600 Cost: 0

In [35]:
model=nn.Linear(4,3)
optimizer=optim.SGD(model.parameters(), lr=0.1)
n_epochs=10000

In [38]:
for epoch in range(n_epochs):
    y_hat=model(x_train)
    cost=F.cross_entropy(y_hat,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 ==0:
        print('Epoch:', epoch, 'Cost: ', cost.item())

Epoch: 0 Cost:  1.4216928482055664
Epoch: 100 Cost:  0.7126542329788208
Epoch: 200 Cost:  0.6324654817581177
Epoch: 300 Cost:  0.5752294063568115
Epoch: 400 Cost:  0.5248818397521973
Epoch: 500 Cost:  0.4773719012737274
Epoch: 600 Cost:  0.4311361014842987
Epoch: 700 Cost:  0.3854140043258667
Epoch: 800 Cost:  0.33987027406692505
Epoch: 900 Cost:  0.2948545515537262
Epoch: 1000 Cost:  0.25447672605514526
Epoch: 1100 Cost:  0.23485183715820312
Epoch: 1200 Cost:  0.2233833223581314
Epoch: 1300 Cost:  0.21295353770256042
Epoch: 1400 Cost:  0.20341810584068298
Epoch: 1500 Cost:  0.19466742873191833
Epoch: 1600 Cost:  0.1866094321012497
Epoch: 1700 Cost:  0.17916636168956757
Epoch: 1800 Cost:  0.17227154970169067
Epoch: 1900 Cost:  0.16586777567863464
Epoch: 2000 Cost:  0.15990564227104187
Epoch: 2100 Cost:  0.1543419510126114
Epoch: 2200 Cost:  0.14913888275623322
Epoch: 2300 Cost:  0.14426323771476746
Epoch: 2400 Cost:  0.13968560099601746
Epoch: 2500 Cost:  0.1353801190853119
Epoch: 2600

In [39]:
prodiction=model(x_train)
print(prodiction)

tensor([[-11.4190,  -0.1089,  11.8240],
        [ -4.3004,   0.4548,   4.3716],
        [-18.3870,   8.3334,  11.4634],
        [-12.6072,   8.7538,   5.5110],
        [  0.9640,   3.5059,  -2.2739],
        [  4.2154,   7.4301,  -9.0254],
        [  7.0721,   4.7320,  -9.1733],
        [ 10.5025,   5.6715, -13.0728]], grad_fn=<AddmmBackward0>)


## 소프트맥스 클래스로 만들기 

In [40]:
class SoftmaxClassaModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(4,3)

    def forward(self, x):
        return self.linear(x)

In [41]:
model=SoftmaxClassaModel()
optimizer=optim.SGD(model.parameters(), lr=0.1)
n_epochs=10000

In [42]:
for epoch in range(n_epochs):
    y_hat=model(x_train)
    cost=F.cross_entropy(y_hat,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 ==0:
        print('Epoch:', epoch, 'Cost: ', cost.item())

Epoch: 0 Cost:  2.637636423110962
Epoch: 100 Cost:  0.6479030251502991
Epoch: 200 Cost:  0.5646426677703857
Epoch: 300 Cost:  0.5110434293746948
Epoch: 400 Cost:  0.4672488868236542
Epoch: 500 Cost:  0.4282805621623993
Epoch: 600 Cost:  0.391924113035202
Epoch: 700 Cost:  0.35674208402633667
Epoch: 800 Cost:  0.32157716155052185
Epoch: 900 Cost:  0.28561723232269287
Epoch: 1000 Cost:  0.2508176863193512
Epoch: 1100 Cost:  0.23210185766220093
Epoch: 1200 Cost:  0.22086557745933533
Epoch: 1300 Cost:  0.21063703298568726
Epoch: 1400 Cost:  0.20127873122692108
Epoch: 1500 Cost:  0.19268494844436646
Epoch: 1600 Cost:  0.18476678431034088
Epoch: 1700 Cost:  0.17744912207126617
Epoch: 1800 Cost:  0.17066752910614014
Epoch: 1900 Cost:  0.16436627507209778
Epoch: 2000 Cost:  0.1584969311952591
Epoch: 2100 Cost:  0.1530178040266037
Epoch: 2200 Cost:  0.14789187908172607
Epoch: 2300 Cost:  0.14308682084083557
Epoch: 2400 Cost:  0.13857412338256836
Epoch: 2500 Cost:  0.13432839512825012
Epoch: 260

In [43]:
prediction=model(x_train)
print(prediction)

tensor([[-11.5036,  -0.2332,  11.5479],
        [ -4.5121,   0.3314,   4.2517],
        [-18.6580,   8.3967,  11.5297],
        [-13.0537,   8.7771,   5.5310],
        [  0.2068,   2.7514,  -3.0321],
        [  3.6674,   6.8846,  -8.6047],
        [  6.2557,   3.9119,  -9.5963],
        [  9.5301,   4.7041, -13.5656]], grad_fn=<AddmmBackward0>)
