In [3]:
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [26]:
data=np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype='float32' )
data

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [27]:
x_data=data[:,0:-1]
t_data=data[:,[-1]]
print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [28]:
x_train=torch.from_numpy(x_data)
t_train=torch.from_numpy(t_data)
print(x_train[:5])
print(t_train[:5])

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


## 모듈로 만들기

In [33]:
model=nn.Linear(3,1)
optimizer=optim.SGD(model.parameters(), lr=1e-6)
nb_epochs=100000

In [37]:
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, t_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400 ==0:
        print('epoch:' , epoch, 'cost: ',cost.item())


epoch: 0 cost:  6.0812859535217285
epoch: 400 cost:  6.0812883377075195
epoch: 800 cost:  6.08126974105835
epoch: 1200 cost:  6.0812602043151855
epoch: 1600 cost:  6.0812602043151855
epoch: 2000 cost:  6.081235408782959
epoch: 2400 cost:  6.081233024597168
epoch: 2800 cost:  6.0812177658081055
epoch: 3200 cost:  6.081206798553467
epoch: 3600 cost:  6.081200122833252
epoch: 4000 cost:  6.081176280975342
epoch: 4400 cost:  6.081167697906494
epoch: 4800 cost:  6.081173896789551
epoch: 5200 cost:  6.081150531768799
epoch: 5600 cost:  6.08114767074585
epoch: 6000 cost:  6.081136703491211
epoch: 6400 cost:  6.081118583679199
epoch: 6800 cost:  6.081106662750244
epoch: 7200 cost:  6.0811052322387695
epoch: 7600 cost:  6.081085681915283
epoch: 8000 cost:  6.081080436706543
epoch: 8400 cost:  6.081061840057373
epoch: 8800 cost:  6.081061363220215
epoch: 9200 cost:  6.081043720245361
epoch: 9600 cost:  6.08104133605957
epoch: 10000 cost:  6.081026554107666
epoch: 10400 cost:  6.0810160636901855


In [45]:
new_data=torch.FloatTensor([[73,80,75]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[152.9326]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.3575, 0.5303, 1.1273]], requires_grad=True), Parameter containing:
tensor([-0.1323], requires_grad=True)]


## 클래스로 만들기 

In [29]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self,x):
        return self.linear(x)

In [22]:
model1=MultiLinearRegressionModel()
print(list(model1.parameters()))
optimizer1=optim.SGD(model1.parameters(), lr=1e-6)

[Parameter containing:
tensor([[ 0.1566, -0.3927, -0.3952]], requires_grad=True), Parameter containing:
tensor([0.5128], requires_grad=True)]


In [41]:
nb1_epochs=200000
for epoch in range(nb1_epochs):
    prediction=model1(x_train)
    cost=F.mse_loss(prediction, t_train)

    optimizer1.zero_grad()
    cost.backward()
    optimizer1.step()

    if epoch%400==0:
        print("Epoch:", epoch, "Cost:", cost.item())

Epoch: 0 Cost: 6.180778980255127
Epoch: 400 Cost: 6.180755138397217
Epoch: 800 Cost: 6.180744647979736
Epoch: 1200 Cost: 6.180740833282471
Epoch: 1600 Cost: 6.180716514587402
Epoch: 2000 Cost: 6.180716514587402
Epoch: 2400 Cost: 6.180705547332764
Epoch: 2800 Cost: 6.180683612823486
Epoch: 3200 Cost: 6.180665493011475
Epoch: 3600 Cost: 6.180658340454102
Epoch: 4000 Cost: 6.180642604827881
Epoch: 4400 Cost: 6.180621147155762
Epoch: 4800 Cost: 6.180604457855225
Epoch: 5200 Cost: 6.18060302734375
Epoch: 5600 Cost: 6.180587291717529
Epoch: 6000 Cost: 6.180570125579834
Epoch: 6400 Cost: 6.18056583404541
Epoch: 6800 Cost: 6.180544376373291
Epoch: 7200 Cost: 6.180538177490234
Epoch: 7600 Cost: 6.180518627166748
Epoch: 8000 Cost: 6.180513858795166
Epoch: 8400 Cost: 6.180489540100098
Epoch: 8800 Cost: 6.180474758148193
Epoch: 9200 Cost: 6.180473804473877
Epoch: 9600 Cost: 6.1804518699646
Epoch: 10000 Cost: 6.180434703826904
Epoch: 10400 Cost: 6.180428981781006
Epoch: 10800 Cost: 6.18041944503784

## 예측 확인 

In [44]:
new_data=torch.FloatTensor([[73,80,75]])
pred_y1=model1(new_data)
print(pred_y1)
print(list(model1.parameters()))

tensor([[152.9758]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.3575, 0.5287, 1.1221]], requires_grad=True), Parameter containing:
tensor([0.4208], requires_grad=True)]
