In [54]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [3]:
model=nn.Linear(1,1) # input_dim=1, output_dim=1
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [5]:
optimizer=optim.SGD(model.parameters(), lr=0.01)

In [8]:
nb_epochs=20000

for epoch in range(nb_epochs):
    prediction=model(x_data)
    cost=F.mse_loss(prediction, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print('Epoch:', epoch, 'Cost:',cost.item())

Epoch: 0 Cost: 5.426272625674855e-11
Epoch: 400 Cost: 5.426272625674855e-11
Epoch: 800 Cost: 5.426272625674855e-11
Epoch: 1200 Cost: 5.426272625674855e-11
Epoch: 1600 Cost: 5.426272625674855e-11
Epoch: 2000 Cost: 5.426272625674855e-11
Epoch: 2400 Cost: 5.426272625674855e-11
Epoch: 2800 Cost: 5.426272625674855e-11
Epoch: 3200 Cost: 5.426272625674855e-11
Epoch: 3600 Cost: 5.426272625674855e-11
Epoch: 4000 Cost: 5.426272625674855e-11
Epoch: 4400 Cost: 5.426272625674855e-11
Epoch: 4800 Cost: 5.426272625674855e-11
Epoch: 5200 Cost: 5.426272625674855e-11
Epoch: 5600 Cost: 5.426272625674855e-11
Epoch: 6000 Cost: 5.426272625674855e-11
Epoch: 6400 Cost: 5.426272625674855e-11
Epoch: 6800 Cost: 5.426272625674855e-11
Epoch: 7200 Cost: 5.426272625674855e-11
Epoch: 7600 Cost: 5.426272625674855e-11
Epoch: 8000 Cost: 5.426272625674855e-11
Epoch: 8400 Cost: 5.426272625674855e-11
Epoch: 8800 Cost: 5.426272625674855e-11
Epoch: 9200 Cost: 5.426272625674855e-11
Epoch: 9600 Cost: 5.426272625674855e-11
Epoch

In [10]:
new_data=torch.FloatTensor([[10]])
y_pred=model(new_data)
print(y_pred)
print(list(model.parameters()))

tensor([[21.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [11]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [12]:
model=nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [13]:
optimizer=optim.SGD(model.parameters(), lr=1e-6)

In [20]:
nb_epochs=20000
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print("Epoch:", epoch, 'Cost:',cost.item())
        print("Prmaters:", list(model.parameters()))

Epoch: 0 Cost: 0.1753249168395996
Prmaters: [Parameter containing:
tensor([[1.0657, 0.5595, 0.3847]], requires_grad=True), Parameter containing:
tensor([0.3584], requires_grad=True)]
Epoch: 400 Cost: 0.17511263489723206
Prmaters: [Parameter containing:
tensor([[1.0658, 0.5593, 0.3848]], requires_grad=True), Parameter containing:
tensor([0.3584], requires_grad=True)]
Epoch: 800 Cost: 0.17490091919898987
Prmaters: [Parameter containing:
tensor([[1.0659, 0.5590, 0.3849]], requires_grad=True), Parameter containing:
tensor([0.3584], requires_grad=True)]
Epoch: 1200 Cost: 0.17468960583209991
Prmaters: [Parameter containing:
tensor([[1.0661, 0.5588, 0.3851]], requires_grad=True), Parameter containing:
tensor([0.3584], requires_grad=True)]
Epoch: 1600 Cost: 0.17448508739471436
Prmaters: [Parameter containing:
tensor([[1.0662, 0.5586, 0.3852]], requires_grad=True), Parameter containing:
tensor([0.3584], requires_grad=True)]
Epoch: 2000 Cost: 0.17427843809127808
Prmaters: [Parameter containing:


In [24]:
print(list(model.parameters()))
new_data=torch.FloatTensor([[80,80,90]])
y_pred=model(new_data)
print(y_pred)

[Parameter containing:
tensor([[1.0701, 0.5501, 0.3897]], requires_grad=True), Parameter containing:
tensor([0.3584], requires_grad=True)]
tensor([[165.0434]], grad_fn=<AddmmBackward0>)


# class 사용 single regression

In [37]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [38]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [39]:
model=LinearRegressionModel()
print(list(model.parameters()))
optimizer=optim.SGD(model.parameters(), lr=0.01)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [40]:
nb_epochs=20000
for epoch in range(nb_epochs):
    prediction=model(x_data)
    cost=F.mse_loss(prediction, t_data)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print('Epoch', epoch, 'Cost:', cost.item())


Epoch 0 Cost: 39.16685104370117
Epoch 400 Cost: 0.01109258271753788
Epoch 800 Cost: 0.0007385412463918328
Epoch 1200 Cost: 4.91717473778408e-05
Epoch 1600 Cost: 3.276181814726442e-06
Epoch 2000 Cost: 2.1860606125301274e-07
Epoch 2400 Cost: 1.4702209227834828e-08
Epoch 2800 Cost: 9.986707016906848e-10
Epoch 3200 Cost: 1.0809344391793374e-10
Epoch 3600 Cost: 5.426272625674855e-11
Epoch 4000 Cost: 5.426272625674855e-11
Epoch 4400 Cost: 5.426272625674855e-11
Epoch 4800 Cost: 5.426272625674855e-11
Epoch 5200 Cost: 5.426272625674855e-11
Epoch 5600 Cost: 5.426272625674855e-11
Epoch 6000 Cost: 5.426272625674855e-11
Epoch 6400 Cost: 5.426272625674855e-11
Epoch 6800 Cost: 5.426272625674855e-11
Epoch 7200 Cost: 5.426272625674855e-11
Epoch 7600 Cost: 5.426272625674855e-11
Epoch 8000 Cost: 5.426272625674855e-11
Epoch 8400 Cost: 5.426272625674855e-11
Epoch 8800 Cost: 5.426272625674855e-11
Epoch 9200 Cost: 5.426272625674855e-11
Epoch 9600 Cost: 5.426272625674855e-11
Epoch 10000 Cost: 5.42627262567485

In [41]:
new_data=torch.FloatTensor([[10]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))


tensor([[21.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [44]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [45]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

In [46]:
model=MultiLinearRegressionModel()
optimizer=optim.SGD(model.parameters(), lr=1e-6)

In [52]:
nb_epochs=20000
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print('Epoch', epoch, 'Cost:', cost.item())

Epoch 0 Cost: 0.1941787451505661
Epoch 400 Cost: 0.1935899257659912
Epoch 800 Cost: 0.19302010536193848
Epoch 1200 Cost: 0.192451611161232
Epoch 1600 Cost: 0.19189170002937317
Epoch 2000 Cost: 0.19133855402469635
Epoch 2400 Cost: 0.1907864362001419
Epoch 2800 Cost: 0.1902484893798828
Epoch 3200 Cost: 0.18971583247184753
Epoch 3600 Cost: 0.18920239806175232
Epoch 4000 Cost: 0.1886906623840332
Epoch 4400 Cost: 0.18820717930793762
Epoch 4800 Cost: 0.18772785365581512
Epoch 5200 Cost: 0.18724951148033142
Epoch 5600 Cost: 0.18680112063884735
Epoch 6000 Cost: 0.18636952340602875
Epoch 6400 Cost: 0.1859409511089325
Epoch 6800 Cost: 0.18551453948020935
Epoch 7200 Cost: 0.18509581685066223
Epoch 7600 Cost: 0.18468864262104034
Epoch 8000 Cost: 0.18428632616996765
Epoch 8400 Cost: 0.18388399481773376
Epoch 8800 Cost: 0.18350458145141602
Epoch 9200 Cost: 0.18313249945640564
Epoch 9600 Cost: 0.18275979161262512
Epoch 10000 Cost: 0.18239223957061768
Epoch 10400 Cost: 0.1820298731327057
Epoch 10800 C

In [53]:
new_data=torch.FloatTensor([[80,90,75]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[164.8235]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[1.0657, 0.5595, 0.3847]], requires_grad=True), Parameter containing:
tensor([0.3584], requires_grad=True)]


In [64]:
data=np.loadtxt('data/data-01-test-score.csv',delimiter=',',dtype='float32')
x_data=data[:, 0:-1]
t_data=data[:,[-1]]
x_train=torch.from_numpy(x_data)
t_train=torch.from_numpy(t_data)
print(x_train[:5])
print(t_train[:5])

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [72]:
model=nn.Linear(3,1)
optimizer=optim.SGD(model.parameters(), lr=1e-6)
nb_epochs=2000000

In [73]:
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, t_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%4000==0:
        print('epoch:', epoch, 'cost:', cost.item())

epoch: 0 cost: 27026.970703125
epoch: 4000 cost: 8.80438232421875
epoch: 8000 cost: 8.115704536437988
epoch: 12000 cost: 7.611212730407715
epoch: 16000 cost: 7.239971160888672
epoch: 20000 cost: 6.9650678634643555
epoch: 24000 cost: 6.760528564453125
epoch: 28000 cost: 6.607356548309326
epoch: 32000 cost: 6.4920125007629395
epoch: 36000 cost: 6.404569149017334
epoch: 40000 cost: 6.337860584259033
epoch: 44000 cost: 6.286663055419922
epoch: 48000 cost: 6.247214317321777
epoch: 52000 cost: 6.2165069580078125
epoch: 56000 cost: 6.192567348480225
epoch: 60000 cost: 6.17379903793335
epoch: 64000 cost: 6.159036159515381
epoch: 68000 cost: 6.147276401519775
epoch: 72000 cost: 6.137905120849609
epoch: 76000 cost: 6.130430698394775
epoch: 80000 cost: 6.124441623687744
epoch: 84000 cost: 6.119614124298096
epoch: 88000 cost: 6.1156535148620605
epoch: 92000 cost: 6.112536430358887
epoch: 96000 cost: 6.109902858734131
epoch: 100000 cost: 6.107823371887207
epoch: 104000 cost: 6.106068134307861
epoch

In [74]:
new_data=torch.FloatTensor([[73,80,75]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[152.9185]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.3575, 0.5308, 1.1290]], requires_grad=True), Parameter containing:
tensor([-0.3132], requires_grad=True)]


In [75]:
class MultiLinearRegressModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

In [76]:
model=MultiLinearRegressionModel()
optimizer=optim.SGD(model.parameters(), lr=1e-6)
nb_epochs=200000

In [77]:
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, t_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%1000==0:
        print('epoch:', epoch, 'cost:',cost.item())

epoch: 0 cost: 16146.9326171875
epoch: 1000 cost: 24.001052856445312
epoch: 2000 cost: 22.7333984375
epoch: 3000 cost: 21.561006546020508
epoch: 4000 cost: 20.476268768310547
epoch: 5000 cost: 19.47236442565918
epoch: 6000 cost: 18.542978286743164
epoch: 7000 cost: 17.68228530883789
epoch: 8000 cost: 16.885038375854492
epoch: 9000 cost: 16.1461238861084
epoch: 10000 cost: 15.461252212524414
epoch: 11000 cost: 14.82608413696289
epoch: 12000 cost: 14.23687744140625
epoch: 13000 cost: 13.690197944641113
epoch: 14000 cost: 13.182641983032227
epoch: 15000 cost: 12.711217880249023
epoch: 16000 cost: 12.27343463897705
epoch: 17000 cost: 11.866589546203613
epoch: 18000 cost: 11.488215446472168
epoch: 19000 cost: 11.136362075805664
epoch: 20000 cost: 10.809165954589844
epoch: 21000 cost: 10.504668235778809
epoch: 22000 cost: 10.221107482910156
epoch: 23000 cost: 9.956875801086426
epoch: 24000 cost: 9.71082592010498
epoch: 25000 cost: 9.481544494628906
epoch: 26000 cost: 9.267688751220703
epoch:

In [78]:
new_data=torch.FloatTensor([[73,80,75]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[152.9016]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.3604, 0.5290, 1.1286]], requires_grad=True), Parameter containing:
tensor([-0.3659], requires_grad=True)]
