In [1]:
import numpy as np

x_data1 = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
t_data1 = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

x_data=np.array(x_data1)
t_data=np.array(t_data1)
print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [9]:
w=np.random.rand(3,1)
b=np.random.rand(1)
print(w,b)

[[0.36369152]
 [0.83541639]
 [0.52193577]] [0.10665271]


In [3]:
def loss_func(x, t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/(len(x))

In [4]:
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) # f(x+delta_x)

        x[idx]=float(tmp_val)-delta_x
        fx2=f(x) # f(x-delta_x)

        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad

In [5]:
def predict(x):
    y=np.dot(x, w)+b
    return y

In [17]:
learning_rate=1e-6

f=lambda x: loss_func(x_data, t_data)

print("Initial error value=", loss_func(x_data, t_data), "Initial w=", w, "b=",b)

for step in range(20001):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step % 400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=",w, "b=",b)

Initial error value= 0.24184189475022774 Initial w= [[0.90530161]
 [0.46658786]
 [0.63771784]] b= [0.12426864]
step= 0 error value= 0.24184136747505874 w= [[0.90530218]
 [0.46658772]
 [0.63771742]] b= [0.12426873]
step= 400 error value= 0.2416312812957604 w= [[0.90552882]
 [0.46653024]
 [0.63754973]] b= [0.12430406]
step= 800 error value= 0.2414228189461653 w= [[0.90575428]
 [0.46647403]
 [0.63738197]] b= [0.12433935]
step= 1200 error value= 0.24121595117979372 w= [[0.90597858]
 [0.46641905]
 [0.63721413]] b= [0.12437461]
step= 1600 error value= 0.24101064936656522 w= [[0.90620174]
 [0.46636529]
 [0.63704622]] b= [0.12440985]
step= 2000 error value= 0.2408068854794861 w= [[0.90642375]
 [0.46631275]
 [0.63687824]] b= [0.12444505]
step= 2400 error value= 0.24060463208184854 w= [[0.90664463]
 [0.46626141]
 [0.6367102 ]] b= [0.12448022]
step= 2800 error value= 0.24040386231448121 w= [[0.90686439]
 [0.46621125]
 [0.63654209]] b= [0.12451537]
step= 3200 error value= 0.24020454988346757 w= [[