In [1]:
import torch

In [2]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [3]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
print(torch.tensor([[1,2],[3,4]]))
#print(torch.tensor([[1,2],[3,4]], device="cuda:0"))
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [5]:
ft=torch.FloatTensor([[1,2],[3,4]])
lt=torch.LongTensor([[1,2],[3,4]])
bt=torch.ByteTensor([[1,2],[3,4]])
print(ft)
print(lt)
print(bt)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


ndarray->torch tensor->ndarray

In [6]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x, type(x))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [7]:
tx=torch.from_numpy(x)
print(tx, type(tx))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32) <class 'torch.Tensor'>


In [8]:
nx=tx.numpy()
print(nx, type(nx))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [9]:
ft=tx.float()
print(ft)
lt=ft.long()
print(lt)
bt=ft.byte()
print(bt)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.uint8)


In [10]:
na=np.arange(1, 13).reshape(3,2,2)
t=torch.from_numpy(na)

In [11]:
print(t.size())
print(t.shape)
print(t.size(2))
print(t.shape[2])
print(t.dim())
print(len(t.size()))
print(t.size(-1))
print(t.shape[-1])

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
2
2
3
3
2
2


In [12]:
a=torch.Tensor([[1,2],[3,4]])
b=torch.Tensor([[1,2],[3,4]])

In [13]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a==b)
print(a!=b)
print(a**b)

tensor([[2., 4.],
        [6., 8.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[True, True],
        [True, True]])
tensor([[False, False],
        [False, False]])
tensor([[  1.,   4.],
        [ 27., 256.]])


In [14]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a//2) #정수몫만 구하기
print(a==2)
print(a>2)
print(a!=2)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[0., 1.],
        [1., 2.]])
tensor([[False,  True],
        [False, False]])
tensor([[False, False],
        [ True,  True]])
tensor([[ True, False],
        [ True,  True]])


In [15]:
c=torch.tensor([1,2])
print(a)
print(a+c)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [4., 6.]])


In [16]:
print(a)
print(b)
print(a.mul_(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])


In [17]:
print(a)
print(a.sum())
print(a.sum(dim=0))
print(a.sum(dim=1))
print(a.sum(dim=-1))

tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor(30.)
tensor([10., 20.])
tensor([ 5., 25.])
tensor([ 5., 25.])


In [18]:
print(t)
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=2))
print(t.sum(dim=-1))

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[15, 18],
        [21, 24]])
tensor([[ 4,  6],
        [12, 14],
        [20, 22]])
tensor([[ 3,  7],
        [11, 15],
        [19, 23]])
tensor([[ 3,  7],
        [11, 15],
        [19, 23]])


In [19]:
ft=t.float()
print(ft.mean())
print(ft.mean(dim=0))
print(ft.mean(dim=1))
print(ft.mean(dim=-1))
print(ft.mean(dim=-1))

tensor(6.5000)
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])
tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])
tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])


In [32]:
a=np.arange(12).reshape(2,3,-1)
b=np.arange(2, 14).reshape(2,3,-1)
c=np.arange(10,16).reshape(3,2)
ta=torch.from_numpy(a)
tb=torch.from_numpy(b)
tc=torch.from_numpy(c)
print(ta)
print(ta.size())
print(tb)
print(tb.size())
print(tc)
print(tc.size())

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]], dtype=torch.int32)
torch.Size([2, 3, 2])
tensor([[[ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13]]], dtype=torch.int32)
torch.Size([2, 3, 2])
tensor([[10, 11],
        [12, 13],
        [14, 15]], dtype=torch.int32)
torch.Size([3, 2])


In [29]:
print(ta+tb)

tensor([[[ 2,  4],
         [ 6,  8],
         [10, 12]],

        [[14, 16],
         [18, 20],
         [22, 24]]], dtype=torch.int32)


In [31]:
print(ta+tc)

tensor([[[10, 12],
         [14, 16],
         [18, 20]],

        [[16, 18],
         [20, 22],
         [24, 26]]], dtype=torch.int32)


In [33]:
x=torch.arange(1,13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
print(x.view(3,4))
print(x.reshape(3,4))
print(x.view(4,3))
print(x.view(3,2,2))
print(x.view(-1,2,3))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [44]:
x1=x.view(3,1,4)
print(x1)

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]])


In [50]:
print(x1.squeeze())

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [53]:
print(x1.unsqueeze(1))
print(x1.size())

tensor([[[[ 1,  2,  3,  4]]],


        [[[ 5,  6,  7,  8]]],


        [[[ 9, 10, 11, 12]]]])
torch.Size([3, 1, 4])


In [55]:
x2=x.view(2,3,2)
x2

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [62]:
print(x2[:,:,1])

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [70]:
x=torch.FloatTensor(4,10)
splits=x.split(3, dim=1)
for s in splits:
    print(s.size())

torch.Size([4, 3])
torch.Size([4, 3])
torch.Size([4, 3])
torch.Size([4, 1])


In [83]:
x=torch.arange(1,65).view(4,4,4)
x

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],

        [[33, 34, 35, 36],
         [37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]],

        [[49, 50, 51, 52],
         [53, 54, 55, 56],
         [57, 58, 59, 60],
         [61, 62, 63, 64]]])

In [78]:
index=torch.LongTensor([0,2])
y=x.index_select(dim=2, index=index)
y

tensor([[[ 1,  3],
         [ 4,  6],
         [ 7,  9]],

        [[10, 12],
         [13, 15],
         [16, 18]],

        [[19, 21],
         [22, 24],
         [25, 27]]])

In [88]:
x=torch.arange(1,13).view(2,2,3)
y=torch.arange(11, 23).view(2,2,3)
print(x)
print(y)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])


In [91]:
z=torch.cat([x,y], dim=-1)
z

tensor([[[ 1,  2,  3, 11, 12, 13],
         [ 4,  5,  6, 14, 15, 16]],

        [[ 7,  8,  9, 17, 18, 19],
         [10, 11, 12, 20, 21, 22]]])

In [102]:
z=torch.stack([x,y], dim=2)
print(z)

tensor([[[[ 1,  2,  3],
          [11, 12, 13]],

         [[ 4,  5,  6],
          [14, 15, 16]]],


        [[[ 7,  8,  9],
          [17, 18, 19]],

         [[10, 11, 12],
          [20, 21, 22]]]])


In [107]:
x.view(1,2,2,3)
y=x.expand(3,2,2,3)
y

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]],


        [[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]],


        [[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]]])

In [112]:
x=torch.arange(1,7).view(2,1,3)
print(x)
y=x.expand(2,2,3)
print(y)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [117]:
x=torch.randperm(100)
x

tensor([15, 12, 42, 91, 51, 67, 46, 27, 70, 18, 72, 25, 75, 47, 44, 82, 68, 92,
        11, 26, 14, 59, 20, 73, 61, 76, 22, 16, 78, 37, 95, 62,  9, 63, 90, 74,
        13,  8, 36, 96, 64, 56, 35,  7, 49, 43, 33, 24, 89, 23, 85, 54, 50, 60,
         6, 41, 88, 99, 66, 97,  3,  4,  2, 84, 80, 34, 19, 71, 81, 40, 29, 32,
        98, 94, 86,  0, 45, 57, 30, 53, 38, 21, 28, 55, 31, 77,  1, 69, 65, 93,
        58, 79, 83, 52, 48, 10,  5, 87, 39, 17])

In [119]:
x=torch.randperm(3**3).view(3,3,-1)
x

tensor([[[20, 16, 12],
         [ 4, 19, 21],
         [26, 18, 17]],

        [[24, 15,  5],
         [ 1, 11, 13],
         [ 0,  3,  9]],

        [[22, 25,  7],
         [ 8, 14,  6],
         [ 2, 10, 23]]])

In [125]:
y=x.argmax(dim=2)
y

tensor([[0, 2, 0],
        [0, 2, 2],
        [1, 1, 2]])

In [126]:
x

tensor([[[20, 16, 12],
         [ 4, 19, 21],
         [26, 18, 17]],

        [[24, 15,  5],
         [ 1, 11, 13],
         [ 0,  3,  9]],

        [[22, 25,  7],
         [ 8, 14,  6],
         [ 2, 10, 23]]])

In [135]:
value, indices=torch.topk(x, k=1, dim=0)
print(value)
print(indices)

tensor([[[24, 25, 12],
         [ 8, 19, 21],
         [26, 18, 23]]])
tensor([[[1, 2, 0],
         [2, 0, 0],
         [0, 0, 2]]])


In [138]:
x=torch.randperm(9).view(3,3)
x

tensor([[4, 1, 7],
        [0, 5, 3],
        [6, 2, 8]])

In [141]:
mask=x<4
mask

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [142]:
y=x.masked_fill(mask, value=0)
y

tensor([[4, 0, 7],
        [0, 5, 0],
        [6, 0, 8]])